version: '3.8'

services:
  user-center-umi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: user-center-umi:dev
    container_name: user-center-umi
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:?err}
    volumes:
      - ~/.ssh:/root/.ssh
    ports:
      - ${PORT:-8010}:8000
